SELECT
  VIDEO.NAME AS video_name,
  VIDEO.NO_OF_views AS no_of_views
FROM
  VIDEO
  INNER JOIN VIDEO_GENRE ON VIDEO.VIDEO_ID = VIDEO_GENRE.VIDEO_ID
WHERE
  VIDEO_GENRE.GENRE_ID IN (201, 202)
GROUP BY
  VIDEO.VIDEO_ID
HAVING
  COUNT(VIDEO.VIDEO_ID) > 1
ORDER BY
  video_name ASC
LIMIT
  5;